Update add-your-certificate.md
GSSoC24/Postman-Challenge pull request #1337
Opened 2024-08-09 05:56 UTC by Amrutha0902

added my name

2024-08-09 06:44 UTC, SakshamShandilya requested changes
Please update your certificate link with a valid one

2024-08-09 09:45 UTC, tanwanimahek approved these changes

2024-08-09 12:57 UTC, dinxsh approved these changes

2024-08-09 12:58 UTC, merged

2024-08-18 04:46 UTC, Amrutha0902 commented
I have still not earned points and its not possible for downloading my GSSOC Certification